### ISSUE TITLE
More APIs

### ISSUE THREAD

**Issue by just4fun** [gogotanc/wxapp-hepan#1]
If you need more APIs, you can have a look [here](https://github.com/just4fun/stuhome/blob/master/src/services/api.js) or dig into [source code](https://github.com/appbyme/mobcent-discuz) directly.

Nice job man.

![tenor-204902703](https://user-images.githubusercontent.com/7512625/39559076-2c5c8782-4ec6-11e8-9fa2-e6d4d8fd2973.gif)

**Comment by gogotanc** [comment]
Wow, cool, thx.
